# Generated by Django 4.1.3 on 2022-12-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_category_alter_blog_image_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
