# Generated by Django 4.1.3 on 2022-12-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='read_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
