# Generated by Django 4.1.3 on 2022-12-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0008_blog_created_at_blog_read_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.ManyToManyField(to='Core.category'),
        ),
    ]
