# Generated by Django 4.1.3 on 2022-12-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='work_status',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
